/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UiKitRouteImport } from './routes/ui-kit'
import { Route as TimeRouteImport } from './routes/time'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TeamRouteImport } from './routes/team'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RotaRouteImport } from './routes/rota'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as NoAccessRouteImport } from './routes/no-access'
import { Route as LeaveRouteImport } from './routes/leave'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaffStaffIdRouteImport } from './routes/staff.$staffId'
import { Route as PortalAccessRouteImport } from './routes/portal_.access'
import { Route as AuthResetRouteImport } from './routes/auth_.reset'

const UiKitRoute = UiKitRouteImport.update({
  id: '/ui-kit',
  path: '/ui-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const TimeRoute = TimeRouteImport.update({
  id: '/time',
  path: '/time',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RotaRoute = RotaRouteImport.update({
  id: '/rota',
  path: '/rota',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const NoAccessRoute = NoAccessRouteImport.update({
  id: '/no-access',
  path: '/no-access',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaveRoute = LeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffStaffIdRoute = StaffStaffIdRouteImport.update({
  id: '/$staffId',
  path: '/$staffId',
  getParentRoute: () => StaffRoute,
} as any)
const PortalAccessRoute = PortalAccessRouteImport.update({
  id: '/portal_/access',
  path: '/portal/access',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/auth_/reset',
  path: '/auth/reset',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/landing': typeof LandingRoute
  '/leave': typeof LeaveRoute
  '/no-access': typeof NoAccessRoute
  '/ops': typeof OpsRoute
  '/portal': typeof PortalRoute
  '/privacy': typeof PrivacyRoute
  '/reports': typeof ReportsRoute
  '/rota': typeof RotaRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRouteWithChildren
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/time': typeof TimeRoute
  '/ui-kit': typeof UiKitRoute
  '/auth/reset': typeof AuthResetRoute
  '/portal/access': typeof PortalAccessRoute
  '/staff/$staffId': typeof StaffStaffIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/landing': typeof LandingRoute
  '/leave': typeof LeaveRoute
  '/no-access': typeof NoAccessRoute
  '/ops': typeof OpsRoute
  '/portal': typeof PortalRoute
  '/privacy': typeof PrivacyRoute
  '/reports': typeof ReportsRoute
  '/rota': typeof RotaRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRouteWithChildren
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/time': typeof TimeRoute
  '/ui-kit': typeof UiKitRoute
  '/auth/reset': typeof AuthResetRoute
  '/portal/access': typeof PortalAccessRoute
  '/staff/$staffId': typeof StaffStaffIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/landing': typeof LandingRoute
  '/leave': typeof LeaveRoute
  '/no-access': typeof NoAccessRoute
  '/ops': typeof OpsRoute
  '/portal': typeof PortalRoute
  '/privacy': typeof PrivacyRoute
  '/reports': typeof ReportsRoute
  '/rota': typeof RotaRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRouteWithChildren
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/time': typeof TimeRoute
  '/ui-kit': typeof UiKitRoute
  '/auth_/reset': typeof AuthResetRoute
  '/portal_/access': typeof PortalAccessRoute
  '/staff/$staffId': typeof StaffStaffIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/landing'
    | '/leave'
    | '/no-access'
    | '/ops'
    | '/portal'
    | '/privacy'
    | '/reports'
    | '/rota'
    | '/settings'
    | '/staff'
    | '/team'
    | '/terms'
    | '/time'
    | '/ui-kit'
    | '/auth/reset'
    | '/portal/access'
    | '/staff/$staffId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/landing'
    | '/leave'
    | '/no-access'
    | '/ops'
    | '/portal'
    | '/privacy'
    | '/reports'
    | '/rota'
    | '/settings'
    | '/staff'
    | '/team'
    | '/terms'
    | '/time'
    | '/ui-kit'
    | '/auth/reset'
    | '/portal/access'
    | '/staff/$staffId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/landing'
    | '/leave'
    | '/no-access'
    | '/ops'
    | '/portal'
    | '/privacy'
    | '/reports'
    | '/rota'
    | '/settings'
    | '/staff'
    | '/team'
    | '/terms'
    | '/time'
    | '/ui-kit'
    | '/auth_/reset'
    | '/portal_/access'
    | '/staff/$staffId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  LandingRoute: typeof LandingRoute
  LeaveRoute: typeof LeaveRoute
  NoAccessRoute: typeof NoAccessRoute
  OpsRoute: typeof OpsRoute
  PortalRoute: typeof PortalRoute
  PrivacyRoute: typeof PrivacyRoute
  ReportsRoute: typeof ReportsRoute
  RotaRoute: typeof RotaRoute
  SettingsRoute: typeof SettingsRoute
  StaffRoute: typeof StaffRouteWithChildren
  TeamRoute: typeof TeamRoute
  TermsRoute: typeof TermsRoute
  TimeRoute: typeof TimeRoute
  UiKitRoute: typeof UiKitRoute
  AuthResetRoute: typeof AuthResetRoute
  PortalAccessRoute: typeof PortalAccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ui-kit': {
      id: '/ui-kit'
      path: '/ui-kit'
      fullPath: '/ui-kit'
      preLoaderRoute: typeof UiKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/time': {
      id: '/time'
      path: '/time'
      fullPath: '/time'
      preLoaderRoute: typeof TimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rota': {
      id: '/rota'
      path: '/rota'
      fullPath: '/rota'
      preLoaderRoute: typeof RotaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/no-access': {
      id: '/no-access'
      path: '/no-access'
      fullPath: '/no-access'
      preLoaderRoute: typeof NoAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leave': {
      id: '/leave'
      path: '/leave'
      fullPath: '/leave'
      preLoaderRoute: typeof LeaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/$staffId': {
      id: '/staff/$staffId'
      path: '/$staffId'
      fullPath: '/staff/$staffId'
      preLoaderRoute: typeof StaffStaffIdRouteImport
      parentRoute: typeof StaffRoute
    }
    '/portal_/access': {
      id: '/portal_/access'
      path: '/portal/access'
      fullPath: '/portal/access'
      preLoaderRoute: typeof PortalAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth_/reset': {
      id: '/auth_/reset'
      path: '/auth/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface StaffRouteChildren {
  StaffStaffIdRoute: typeof StaffStaffIdRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffStaffIdRoute: StaffStaffIdRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  LandingRoute: LandingRoute,
  LeaveRoute: LeaveRoute,
  NoAccessRoute: NoAccessRoute,
  OpsRoute: OpsRoute,
  PortalRoute: PortalRoute,
  PrivacyRoute: PrivacyRoute,
  ReportsRoute: ReportsRoute,
  RotaRoute: RotaRoute,
  SettingsRoute: SettingsRoute,
  StaffRoute: StaffRouteWithChildren,
  TeamRoute: TeamRoute,
  TermsRoute: TermsRoute,
  TimeRoute: TimeRoute,
  UiKitRoute: UiKitRoute,
  AuthResetRoute: AuthResetRoute,
  PortalAccessRoute: PortalAccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
